### PR TITLE
Add datavolumes support

### PR DESCRIPTION
**Pull request by machacekondra**
Adding WIP so we can agree on design. Other than that it's working solution.

### CODE REVIEW

**Comment by machacekondra** [comment]
rebased

**Comment by mmazur** [comment]
I think the proper way to do this is to integrate it the same way we've done pvc's. So this should work:

```
cpu_cores: 1
disks:
  - name: d1
    volume:
      (…)
    disk:
      bus: virtio
  - name: d2
    datavolume:
      all the datavolume-y definitions
    disk:
      bus: virtio
```

with all the magic required to get the datavolumes spec properly generated happening behind the scenes.

My brain fails me, so I'm unable to think through how the datavolume spec should potentially be flattened, but I suppose that's an option.

**Comment by machacekondra** [comment]
I was afraid it would bring too much nesting. Like:
```yaml
kubevirt_vm:
  ...
  disks:
    - name: disk
      datavolume:
        source:
	  http:
	    url: https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2
	pvc:
	  accessModes:
	    - ReadWriteOnce
	  storage: 2Gi
      disk:
        bus: virtio
```

But yes it's an option. Note that we do the same with cloud_init it's top level parameter as well, which create volume&disk. So I though we should put this top level as well because it creates those behind scene as well.

**Comment by machacekondra** [comment]
Yeah, I will change this PR to test playbook and move code to Ansible repo.

**Comment by pkliczewski** [comment]
> Yeah, I will change this PR to test playbook and move code to Ansible repo.

Do we need this PR if we want to push it to Ansible repo?

**Comment by mmazur** [comment]
Yeah, we need to make sure to get everything pushed this week, even if it's not finished, to make sure the PR's are "old enough" to have a chance to get merged.

**Comment by machacekondra** [comment]
Moved here: https://github.com/ansible/ansible/pull/52998

**Pull request closed without merging**
