### PR TITLE
Drop cdi_upload module along with all module code

### PR DESCRIPTION
**Pull request by mmazur**
Let's maybe not merge this until tomorrow, when I'll post the upstream PR.

### CODE REVIEW

**Comment by mmazur** [comment]
@pkliczewski @machacekondra mergeable now

**Comment by pkliczewski** [comment]
@machacekondra review?

**Comment by machacekondra** [comment]
If it's merged, would be nice to add a playbook with a test.

**Comment by mmazur** [comment]
@machacekondra test for what?

**Comment by machacekondra** [comment]
@mmazur integration test for `kubevirt_cdi_upload`

**Pull request merged**
