### PR TITLE
Move unit tests into proper directories

### PR DESCRIPTION
**Pull request by mmazur**
Previous directory structure would conflict with upstream ansible. This one doesn't.

(It's a bit easier for me to push this against current master, rebase Ondra's patch against this and continue work. If that's a hassle, I can just go straight to Ondra's patch.)

### CODE REVIEW

**Comment by pkliczewski** [comment]
@machacekondra please take a look. It looks OK to me.

**Comment by mmazur** [comment]
@machacekondra, if you're about to merge the dyn client support, I can drop this patch and redo it on top of dynclient. There are some other „moving stuff around” patches waiting as well.

**Comment by machacekondra** [comment]
@pkliczewski @mmazur I think Piotr will merge it soon, so it would be nice if you can rebase, when Piotr will merge it.

**Comment by pkliczewski** [comment]
@machacekondra @mmazur Merged. Please rebase

**Comment by mmazur** [comment]
I'll send a better one in a separate PR.

**Pull request closed without merging**
