### PR TITLE
Remove kubevirt_raw module

### PR DESCRIPTION
**Pull request by machacekondra**

### CODE REVIEW

**Comment by machacekondra** [comment]
@mmazur @vatsalparekh @pkliczewski @adityaramteke

**Comment by mmazur** [comment]
Yeah, I'm pretty sure we should hold up on this one until we have the other modules in place.

**Comment by machacekondra** [comment]
Which one? I think we should go, the only missing thing is waiting for PVC to be ready, I think that's ok. I added WA for that

**Comment by machacekondra** [comment]
I would really like to do a cleanup of the tests and start testing adding proper examples.

**Pull request merged**
