### PR TITLE
Limit reqs to openshift client <0.9.0

### PR DESCRIPTION
**Pull request by mmazur**
I've seen the changes in 0.9. Our code won't work with that version without some serious changes.

### CODE REVIEW

**Comment by pkliczewski** [comment]
Please provide more information what are the issues

**Comment by mmazur** [comment]
Until it gets released and we commit to porting to it, there's no point in spending too much time investigating the current state of it. I did try using master openshift-restlclient-python when doing the api detection thing and one thing I can say is that it looks noticeably incompatible. For example `openshift.watch` (which we use in everything) doesn't exist anymore (`watch.py` file is like completely gone). And there were some definitions missing. Basically supporting it will be a separate case.

**Comment by machacekondra** [comment]
Maybe better to open an issue on their repo that they break backward compatibility?

**Comment by mmazur** [comment]
I'm pretty sure if something's versioned 0.X, it's because the author doesn't want to guarantee compatibility yet.

(This is btw explicitly stated on semver.org, item 4, which I've seen multiple references to over the past few months in various projects, so I'm assuming it has become a sort of standard for versioning stuff.)

**Comment by pkliczewski** [comment]
We can open the issue and add comment to this change that it will be resolved in the future.

**Comment by mmazur** [comment]
You mean:

1. add issue in our repo: add compatibility with openshift-restclient 0.9+
2. add link to this in commitlog

?

**Comment by mmazur** [comment]
Done. Created an issue and added a link to the cilog.

**Comment by pkliczewski** [comment]
@machacekondra review?

**Pull request merged**
