### PR TITLE
Update playbooks to use kubevirt_pvc module

### PR DESCRIPTION
**Pull request by mmazur**
Once https://github.com/ansible/ansible/pull/53327 gets merged, this should as well.

### CODE REVIEW

**Comment by machacekondra** [comment]
Can you also please add it to `all.yml` so it's executed by the test?

**Comment by mmazur** [comment]
Yup, done.

**Comment by mmazur** [comment]
Ok, this is done. I'm not entirely clear on how the tests are done. Is the travis CI thing all that is gonna run?

**Comment by machacekondra** [comment]
Not sure I understand. Yes, the test just run the `all.yml` playbook, with your test. it's failing on timeout, so please increase timeout for waiting for the PVC to be ready.

**Comment by mmazur** [comment]
Current timeout is 7.5 minutes and it still fails with "pending". Any ideas?

**Comment by machacekondra** [comment]
try `storage_class_name=standard`

**Comment by mmazur** [comment]
Ha, that worked. Ok, tests passed.

**Pull request merged**
